const STATUS = {
    READY_TO_SEARCH: "READY_TO_SEARCH",
    SEARCHING: "SEARCHING",
    READY_TO_CONVERT: "READY_TO_CONVERT",
    CONVERTING: "CONVERTING",
    READY_TO_DOWNLOAD: "READY_TO_DOWNLOAD"
}

export default STATUS;